name: textlint

on: [pull_request]

jobs:
  textlint:
    name: runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: textlint-github-pr-check
        uses: tsuyoshicho/action-textlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          textlint_flags: 'docs/**'
      - name: textlint-github-check
        uses: tsuyoshicho/action-textlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          textlint_flags: 'docs/**'
      - name: textlint-github-pr-review
        uses: tsuyoshicho/action-textlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          textlint_flags: 'docs/**'
